parameters:
    security.exception_listener.class: Packagist\WebBundle\Security\ExceptionListener

services:
    packagist.user_provider:
        class: Packagist\WebBundle\Security\Provider\UserProvider
        public: false
        arguments: ['@fos_user.user_manager', '@fos_user.user_provider.username_email']

    packagist.acl_package_checker:
        class: Packagist\WebBundle\Security\Acl\PackagesAclChecker
        arguments: ['@doctrine']

    packagist.packages.acl_voter:
        class: Packagist\WebBundle\Security\Acl\PackagesAclVoter
        arguments: ['@packagist.acl_package_checker']
        tags:
            - { name: security.voter }

    packagist.security.authentication.provider:
        class: Packagist\WebBundle\Security\Api\ApiTokenProvider
        public: false
        arguments:
            - '@packagist.user_provider'
            - ~

    packagist.security.authentication.listener:
        class: Packagist\WebBundle\Security\Api\ApiBasicAuthenticationListener
        arguments: ['@security.token_storage', '@security.authentication.manager', ~, ~, '@logger']
        public: false

    packagist.authentication.entry_point:
        class: Packagist\WebBundle\Security\Api\ApiBasicAuthenticationEntryPoint
        public: false
