parameters:
    packagist_web.archive: []

services:
    packagist.twig.extension:
        class: Packagist\WebBundle\Twig\PackagistExtension
        arguments: [ '@service_container' ]
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    packagist.cache_listener:
        class: Packagist\WebBundle\EventListener\CacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }

    packagist.logged_in_user_cannot_register_listener:
        class: Packagist\WebBundle\EventListener\LoggedInUserCannotRegisterListener
        arguments:
            - '@security.authorization_checker'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    packagist.registration_listener:
        class: Packagist\WebBundle\EventListener\RegistrationListener
        arguments: [ '@fos_user.util.token_generator' ]
        tags:
            - { name: kernel.event_subscriber }

    packagist.user_repository:
        class: Packagist\WebBundle\Entity\UserRepository
        factory: ['@doctrine', getRepository]
        arguments: ['PackagistWebBundle:User']

    packagist.package_repository:
        class: Packagist\WebBundle\Entity\PackageRepository
        factory: ['@doctrine', getRepository]
        arguments: ['PackagistWebBundle:Package']

    packagist.version_repository:
        class: Packagist\WebBundle\Entity\VersionRepository
        factory: ['@doctrine', getRepository]
        arguments: ['PackagistWebBundle:Version']
        calls:
            - [ setRedis, [ '@snc_redis.cache_client' ]]

    packagist.package_updater:
        class: Packagist\WebBundle\Package\Updater
        arguments: ['@doctrine', '@packagist.dist_config']

    packagist.dist_config:
        class: Packagist\WebBundle\Service\DistConfig
        arguments: ['@router', '%packagist_web.archive%']

    packagist.in_memory_dumper:
        class: Packagist\WebBundle\Package\InMemoryDumper
        arguments: ['@doctrine', '@packagist.acl_package_checker', '@router']
        public: true

    fos_user.util.user_manipulator:
        class: Packagist\WebBundle\Util\UserManipulator
        arguments:
            - '@fos_user.user_manager'
            - '@fos_user.util.token_generator'
            - '@event_dispatcher'
            - '@request_stack'

    fos_user.form.package_type:
        class: Packagist\WebBundle\Form\Type\PackageType
        arguments: ['@packagist.package_manager']
        tags:
            - { name: form.type }

    packagist.oauth.registration_form:
        factory: ['@form.factory', create]
        class: Symfony\Component\Form\Form
        arguments:
            - 'packagist_oauth_user_registration'

    packagist.download_manager:
        class: Packagist\WebBundle\Model\DownloadManager
        arguments:
            - '@snc_redis.default_client'

    packagist.provider_manager:
        class: Packagist\WebBundle\Model\ProviderManager
        public: true
        arguments:
            - '@snc_redis.default_client'
            - '@packagist.package_repository'

    packagist.favorite_manager:
        class: Packagist\WebBundle\Model\FavoriteManager
        arguments:
            - '@snc_redis.default_client'
            - '@packagist.package_repository'
            - '@packagist.user_repository'

    packagist.package_manager:
        class: Packagist\WebBundle\Model\PackageManager
        arguments:
            - '@doctrine'
            - '@mailer'
            - '@twig'
            - '@logger'
            - { from: '%mailer_from_email%', fromName: '%mailer_from_name%' }
            - '@packagist.provider_manager'
            - '@packagist.in_memory_dumper'
            - '@security.authorization_checker'
            - '@packagist_factory'
            - '@packagist_cache'

    Packagist\WebBundle\Model\PackageManager:
        alias: packagist.package_manager
        public: true

    packagist.profile.form.type:
        class: Packagist\WebBundle\Form\Type\ProfileFormType
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: form.type }

    packagist.permission_collection.form.type:
        class: Packagist\WebBundle\Form\Type\GroupAclPermissionCollectionType
        arguments: ['@doctrine']
        tags:
            - { name: form.type }

    packagist.menu_builder:
        class: Packagist\WebBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory', '@security.token_storage', '@translator', '@security.authorization_checker']

    packagist.menu.user:
        class: Knp\Menu\MenuItem
        factory: ['@packagist.menu_builder', createUserMenu]
        tags:
            - { name: knp_menu.menu, alias: user_menu }

    packagist.menu.profile:
        class: Knp\Menu\MenuItem
        factory: ['@packagist.menu_builder', createProfileMenu]
        tags:
            - { name: knp_menu.menu, alias: profile_menu }

    packagist.menu.admin:
        class: Knp\Menu\MenuItem
        factory: ['@packagist.menu_builder', createAdminMenu]
        tags:
            - { name: knp_menu.menu, alias: admin_menu }

    packagist.queue_worker:
        class: Packagist\WebBundle\Service\QueueWorker
        arguments:
            - "@packagist.log_resetter"
            - "@snc_redis.default_client"
            - "@doctrine"
            - "@logger"
            - 'package:updates': '@updater_worker'

    scheduler:
        class: Packagist\WebBundle\Service\Scheduler
        arguments: ["@snc_redis.default_client", "@doctrine"]

    locker:
        class: Packagist\WebBundle\Service\Locker
        arguments: ["@doctrine"]

    updater_worker:
        class: Packagist\WebBundle\Service\UpdaterWorker
        arguments:
            - "@logger"
            - "@doctrine"
            - "@packagist.package_updater"
            - "@locker"
            - "@scheduler"
            - "@packagist.package_manager"
            - "@packagist.download_manager"
            - "@packagist_factory"

    packagist.log_resetter:
        class: Packagist\WebBundle\Service\LogResetter
        arguments: ['@service_container', '%fingers_crossed_handlers%']

    packagist.console_stack_trace_line_formatter:
        class: Symfony\Bridge\Monolog\Formatter\ConsoleFormatter
        arguments: []

    packagist_factory:
        class: Packagist\WebBundle\Composer\PackagistFactory
        public: true
        arguments:
            - '@Packagist\WebBundle\Composer\VcsRepositoryFactory'
            - ~
            - '%github_no_api%'

    Packagist\WebBundle\Service\DistManager:
        public: true
        arguments:
            - '@packagist.dist_config'
            - '@packagist_factory'

    Packagist\WebBundle\Composer\PackagistFactory:
        alias: packagist_factory
        public: true

    Packagist\WebBundle\Util\ChangelogUtils:
        public: true
        arguments:
            - '@packagist_factory'

    Packagist\WebBundle\Composer\VcsDriverFactory:
        public: true

    Packagist\WebBundle\Composer\VcsRepositoryFactory:
        public: true
        arguments:
            - '@Packagist\WebBundle\Composer\VcsDriverFactory'

    Packagist\WebBundle\Validator\Constraint\PackageUniqueValidator:
        arguments:
            - '@doctrine'
            - '@router'
        tags:
            - { name: validator.constraint_validator }

    Packagist\WebBundle\Form\Type\WebhookType:
        arguments:
            - '@security.token_storage'
            - '@packagist.payload_rendered'
        tags:
            - { name: form.type }

    Packagist\WebBundle\Command\CreateUserCommand:
        arguments:
            - '@fos_user.util.user_manipulator'
            - '@fos_user.user_manager'
        tags:
            - { name: console.command }

    # Form extensions
    Packagist\WebBundle\Form\Extension\TooltipExtension:
        tags:
            - { name: form.type_extension, extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType' }

    packagist_cache:
        parent: doctrine_cache.abstract.file_system
        arguments:
            - '%kernel.cache_dir%/packagist'
