Packagist\WebBundle\Entity\Package:
    constraints:
        - Packagist\WebBundle\Validator\Constraint\PackageUnique: { groups: [Create] }
        - Packagist\WebBundle\Validator\Constraint\PackageRepository: { groups: [Update, Create] }
    properties:
        repository:
            - NotBlank: ~
