monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels: ['!event']
            excluded_404s:
                - ^/
        nested:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            include_stacktraces: true

        console_debug:
            type:   console
            verbosity_levels:
                VERBOSITY_NORMAL: EMERGENCY
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            formatter: packagist.console_stack_trace_line_formatter
