_packagist:
    resource: '@PackagistWebBundle/Controller'
    type:     annotation

fos_user_profile:
    resource: '@FOSUserBundle/Resources/config/routing/profile.xml'
    prefix: /profile

fos_user_profile_show:
    path: /profile/
    defaults: { _controller: PackagistWebBundle:User:myProfile }
    methods: [GET]

fos_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /resetting

fos_user_change_password:
    resource: '@FOSUserBundle/Resources/config/routing/change_password.xml'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
